name: CICD STATIC APP DEPLOYMENT

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy via SSH
        uses: appleboy/sh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_username }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/stop-watch-app
            sudo git pull origin main
            echo "Done"
